apiVersion: apps/v1
kind: Deployment
metadata:
  name:  rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - image:  rabbitmq:4.0-management
          name:  rabbitmq
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 5672
            - containerPort: 15672